import { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for Repolyze — AI-powered GitHub repository analysis.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto max-w-3xl px-4 py-12 sm:py-16">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors mb-8"
        >
          <ArrowLeft className="size-4" />
          Back to home
        </Link>

        <h1 className="text-3xl sm:text-4xl font-semibold tracking-tight mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground mb-10">
          Last updated: February 26, 2026
        </p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8 text-sm leading-relaxed text-muted-foreground">
          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Repolyze (&quot;the Service&quot;), operated by Ossium Inc., you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">2. Description of Service</h2>
            <p>
              Repolyze is an AI-powered tool that analyzes public GitHub repositories to provide insights on code quality, architecture, security vulnerabilities, and actionable improvement suggestions. The Service is provided &quot;as is&quot; and &quot;as available&quot;.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">3. User Accounts</h2>
            <p>
              You may sign in using third-party authentication providers (GitHub, Google). By signing in, you grant us access to basic profile information (name, email, avatar) as provided by these services. You are responsible for maintaining the security of your account.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Use the Service to analyze private repositories without authorization.</li>
              <li>Attempt to circumvent rate limits or access restrictions.</li>
              <li>Use automated tools to scrape or overload the Service.</li>
              <li>Reverse engineer, decompile, or attempt to extract the source code of the Service&apos;s proprietary components.</li>
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">5. Rate Limits</h2>
            <p>
              Anonymous users are subject to a daily limit of repository analyses. Authenticated users receive higher or unlimited usage. We reserve the right to modify these limits at any time without prior notice.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">6. AI-Generated Content</h2>
            <p>
              Analysis results are generated by AI and are provided for informational purposes only. Repolyze does not guarantee the accuracy, completeness, or reliability of any AI-generated insights. You should independently verify any findings before acting on them.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">7. Intellectual Property</h2>
            <p>
              The Service, including its design, logos, and underlying technology, is the property of Ossium Inc. You retain all rights to your repositories and code. We do not claim ownership of any code analyzed through the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Ossium Inc. shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time, with or without cause, and with or without notice. Upon termination, your right to use the Service will immediately cease.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">10. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. We will notify users of material changes by posting the updated terms on this page with a revised &quot;Last updated&quot; date. Continued use of the Service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">11. Contact</h2>
            <p>
              If you have questions about these Terms, please contact us at{" "}
              <a href="https://x.com/ossium_inc" target="_blank" rel="noopener noreferrer" className="text-foreground underline hover:no-underline">
                @ossium_inc on X
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
